name: CI (e2e)

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  workflow_call:
  merge_group:

concurrency:
  group: ci-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-for-e2e-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: save trustify-ui image
        run: |
          docker build . -t ghcr.io/trustification/trustify-ui:pr-test -f Dockerfile
          docker save -o /tmp/trustify-ui.tar ghcr.io/trustification/trustify-ui:pr-test

      - name: Upload trustify-ui image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trustify-ui
          path: /tmp/trustify-ui.tar
          retention-days: 1

  discover-envs-for-e2e-ci:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-outputs.outputs.image_tag }}
    steps:
      - name: Extract env vars for main
        shell: bash
        if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || (github.event_name != 'pull_request' && github.ref == 'refs/heads/main') }}
        run: |
          echo "image_tag=latest" >> $GITHUB_ENV
      - name: Extract env vars for other branches on PR
        shell: bash
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'main' }}
        run: |
          branch=${{ github.event.pull_request.base.ref }}
          branch_version="${branch#release/}"
          echo "image_tag=$branch_version" >> $GITHUB_ENV
      - name: Extract env vars for other branches on Push
        shell: bash
        if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'refs/heads/main') == false }}
        run: |
          branch=$(echo ${GITHUB_REF#refs/heads/})
          branch_version="${branch#release/}"
          echo "image_tag=$branch_version" >> $GITHUB_ENV
      - name: Set outputs
        id: set-outputs
        run: |
          echo "image_tag=${{ env.image_tag }}" >> "$GITHUB_OUTPUT"

  run-e2e-ci:
    needs:
      - build-and-upload-for-e2e-ci
      - discover-envs-for-e2e-ci
    uses: ./.github/workflows/ci-e2e-template.yaml
    with:
      artifact: trustify-ui
      ui_image: ghcr.io/trustification/trustify-ui:pr-test
      server_image: ghcr.io/trustification/trustd:${{ needs.discover-envs-for-e2e-ci.outputs.image_tag }}

  coverage:
    needs: run-e2e-ci
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: install dependencies
        run: npm clean-install --verbose --ignore-scripts --no-audit

      - name: install trustify
        id: install-trustify
        uses: ./.github/actions/start-trustify
        with:
          ui_image: ${{ inputs.ui_image }}
          server_image: ${{ inputs.server_image }}
          server_db_image: ${{ inputs.server_db_image }}

      - name: trustify-ui - start in dev mode
        run: |
          AUTH_REQUIRED=false npm run start:dev & echo "dev ui started"
      - name: trustify-ui - wait
        run: |
          until curl -s http://localhost:3000 | grep -qi "<html"; do
            echo "Waiting for HTML page"
            sleep 2
          done

      - name: Tests with coverage
        working-directory: e2e
        run: |
          PW_TEST_CONNECT_WS_ENDPOINT=ws://localhost:${{ steps.install-trustify.outputs.playwright_port }}/ TRUSTIFY_UI_URL=http://localhost:3000 AUTH_REQUIRED=false npm run test:ui
          ls -la .nyc_output

      - name: Generate coverage report
        run: |
          npx nyc report --temp-dir e2e/.nyc_output --reporter=html --reporter=text --reporter=lcov
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: trustification/trustify-ui