name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "v*"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: trustification/release-tools/.github/workflows/build-push-images.yaml@main
    with:
      registry: "ghcr.io"
      image_name: "${{ github.repository_owner }}/trustify-ui"
      containerfile: "./Dockerfile"
      architectures: '[ "amd64", "arm64" ]'
      
      # 2023-03-19: currently needed for npm@10
      extra-args: "--ulimit nofile=4096:4096"
      pre_build_cmd: |
        sed -i '/RUN npm clean-install/i RUN npm install -g npm@9' Dockerfile
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}